name = "redyhealth"
main = "worker.js"
compatibility_date = "2026-09-05"

routes = [
	{ pattern = "redyhealth.co", custom_domain = true },
	{ pattern = "www.redyhealth.co", custom_domain = true }
]

[assets]
directory = "."
binding = "ASSETS"
